/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoventas;

import java.awt.Color;

/**
 *
 * @author david
 */
public class MenuVentas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaVentas
     */
    public MenuVentas() {
        initComponents();
        setLocationRelativeTo(null);

        txtNombreProducto.setText("Ingrese el nombre del producto...");
        txtNombreProducto.setForeground(Color.GRAY);
        txtNombreProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtNombreProducto.getText().equals("Ingrese el nombre del producto...")) {
                    txtNombreProducto.setText("");
                    txtNombreProducto.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtNombreProducto.getText().trim().isEmpty()) {
                    txtNombreProducto.setText("Ingrese el nombre del producto...");
                    txtNombreProducto.setForeground(Color.GRAY);
                }
            }
        });

        lblnroSerie.setText("nro Serie");
        lblnroSerie.setForeground(Color.GRAY);
        lblnroSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (lblnroSerie.getText().equals("nro Serie")) {
                    lblnroSerie.setText("");
                    lblnroSerie.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (lblnroSerie.getText().trim().isEmpty()) {
                    lblnroSerie.setText("nro Serie");
                    lblnroSerie.setForeground(Color.GRAY);
                }
            }
        });

        lblnroVenta.setText("nro Venta");
        lblnroVenta.setForeground(Color.GRAY);
        lblnroVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (lblnroVenta.getText().equals("nro Venta")) {
                    lblnroVenta.setText("");
                    lblnroVenta.setForeground(Color.BLACK);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (lblnroVenta.getText().trim().isEmpty()) {
                    lblnroVenta.setText("nro Venta");
                    lblnroVenta.setForeground(Color.GRAY);
                }
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanelIzquierdo = new javax.swing.JPanel();
        JPanelLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        JPanelBotonesIzq = new javax.swing.JPanel();
        btnPrincipal = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblVentas = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        lblTotalVenta = new javax.swing.JLabel();
        lblMostrar = new javax.swing.JLabel();
        lblRegistros = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CBoxRegistros = new javax.swing.JComboBox<>();
        btnRealizarVenta = new javax.swing.JButton();
        btnRealizarVenta1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtTotalVentaframe = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblDocumento = new javax.swing.JLabel();
        lblTipoPago = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblSerie = new javax.swing.JLabel();
        lblNroVenta = new javax.swing.JLabel();
        lblnroSerie = new javax.swing.JLabel();
        lblnroVenta = new javax.swing.JLabel();
        lblEfectivoRecibido = new javax.swing.JLabel();
        txtCantidadEfectivo = new javax.swing.JTextField();
        lblEfectivo = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblIVANumero = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblSubTotalNumero = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalNumero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VENTAS");

        jPanel1.setBackground(new java.awt.Color(32, 42, 56));

        JPanelIzquierdo.setBackground(new java.awt.Color(25, 34, 45));

        JPanelLogo.setBackground(new java.awt.Color(35, 46, 61));

        lblLogo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblLogo.setForeground(new java.awt.Color(88, 111, 131));
        lblLogo.setText("RAMIFY");

        javax.swing.GroupLayout JPanelLogoLayout = new javax.swing.GroupLayout(JPanelLogo);
        JPanelLogo.setLayout(JPanelLogoLayout);
        JPanelLogoLayout.setHorizontalGroup(
            JPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLogoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(48, 48, 48))
        );
        JPanelLogoLayout.setVerticalGroup(
            JPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        JPanelBotonesIzq.setBackground(new java.awt.Color(30, 40, 53));

        btnPrincipal.setText("PRINCIPAL");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        btnProductos.setText("PRODUCTOS");
        btnProductos.setMaximumSize(new java.awt.Dimension(85, 23));
        btnProductos.setMinimumSize(new java.awt.Dimension(85, 23));
        btnProductos.setPreferredSize(new java.awt.Dimension(85, 23));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnVentas.setText("VENTAS");
        btnVentas.setMaximumSize(new java.awt.Dimension(85, 23));
        btnVentas.setMinimumSize(new java.awt.Dimension(85, 23));
        btnVentas.setPreferredSize(new java.awt.Dimension(85, 23));

        btnCompras.setText("Compras");
        btnCompras.setMaximumSize(new java.awt.Dimension(85, 23));
        btnCompras.setMinimumSize(new java.awt.Dimension(85, 23));
        btnCompras.setPreferredSize(new java.awt.Dimension(85, 23));

        btnConfiguracion.setText("Configuración");
        btnConfiguracion.setMaximumSize(new java.awt.Dimension(85, 23));
        btnConfiguracion.setMinimumSize(new java.awt.Dimension(85, 23));
        btnConfiguracion.setPreferredSize(new java.awt.Dimension(85, 23));

        javax.swing.GroupLayout JPanelBotonesIzqLayout = new javax.swing.GroupLayout(JPanelBotonesIzq);
        JPanelBotonesIzq.setLayout(JPanelBotonesIzqLayout);
        JPanelBotonesIzqLayout.setHorizontalGroup(
            JPanelBotonesIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBotonesIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelBotonesIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelBotonesIzqLayout.setVerticalGroup(
            JPanelBotonesIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelBotonesIzqLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout JPanelIzquierdoLayout = new javax.swing.GroupLayout(JPanelIzquierdo);
        JPanelIzquierdo.setLayout(JPanelIzquierdoLayout);
        JPanelIzquierdoLayout.setHorizontalGroup(
            JPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPanelIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelBotonesIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelIzquierdoLayout.setVerticalGroup(
            JPanelIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelIzquierdoLayout.createSequentialGroup()
                .addComponent(JPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelBotonesIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(36, 49, 64));
        jPanel2.setForeground(new java.awt.Color(36, 49, 64));
        jPanel2.setPreferredSize(new java.awt.Dimension(169, 43));

        lblVentas.setBackground(new java.awt.Color(0, 0, 0));
        lblVentas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(141, 160, 180));
        lblVentas.setText("VENTAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        txtNombreProducto.setColumns(20);
        txtNombreProducto.setLineWrap(true);
        txtNombreProducto.setRows(5);
        txtNombreProducto.setToolTipText("Ingrese el nombre del producto.");
        txtNombreProducto.setWrapStyleWord(true);
        txtNombreProducto.setAutoscrolls(false);
        txtNombreProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 2, true));

        jPanel3.setBackground(new java.awt.Color(36, 49, 64));

        lblTotalVenta.setBackground(new java.awt.Color(141, 160, 176));
        lblTotalVenta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotalVenta.setForeground(new java.awt.Color(141, 160, 176));
        lblTotalVenta.setText("Total venta:  ");

        lblMostrar.setBackground(new java.awt.Color(141, 160, 176));
        lblMostrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMostrar.setForeground(new java.awt.Color(141, 160, 176));
        lblMostrar.setText("Mostrar");

        lblRegistros.setBackground(new java.awt.Color(141, 160, 176));
        lblRegistros.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRegistros.setForeground(new java.awt.Color(141, 160, 176));
        lblRegistros.setText("registros");

        CBoxRegistros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "20", "30" }));
        CBoxRegistros.setToolTipText("");
        CBoxRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBoxRegistrosActionPerformed(evt);
            }
        });

        btnRealizarVenta.setBackground(new java.awt.Color(51, 102, 255));
        btnRealizarVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarVenta.setText("Realizar Venta");
        btnRealizarVenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(141, 160, 176), 1, true));
        btnRealizarVenta.setBorderPainted(false);
        btnRealizarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnRealizarVenta1.setBackground(new java.awt.Color(255, 0, 51));
        btnRealizarVenta1.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizarVenta1.setText("Vaciar Lista");
        btnRealizarVenta1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(141, 160, 176), 1, true));
        btnRealizarVenta1.setBorderPainted(false);
        btnRealizarVenta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRealizarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnRealizarVenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CBoxRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegistros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRealizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRealizarVenta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBoxRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegistros))
                .addGap(137, 137, 137))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtTotalVentaframe.setBackground(new java.awt.Color(51, 102, 255));
        txtTotalVentaframe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTotalVentaframe.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalVentaframe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotalVentaframe.setText("TOTAL VENTA: ");
        txtTotalVentaframe.setBorder(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boleta", "Factura", "Ticket" }));

        lblDocumento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDocumento.setText("Documento*");

        lblTipoPago.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTipoPago.setText("Tipo Pago*");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", " " }));

        lblSerie.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSerie.setText("Serie");

        lblNroVenta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNroVenta.setText("Nro. Venta");

        lblnroSerie.setBackground(new java.awt.Color(204, 204, 204));
        lblnroSerie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        lblnroVenta.setBackground(new java.awt.Color(204, 204, 204));
        lblnroVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        lblEfectivoRecibido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEfectivoRecibido.setText("Efectivo Recibido");

        txtCantidadEfectivo.setToolTipText("Cantidad de efectivo recibida");

        lblEfectivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEfectivo.setText("Efectivo = $");

        lblCambio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCambio.setText("Cambio = $");

        lblIVA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIVA.setText("IVA (16%)");

        lblIVANumero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblIVANumero.setText("s");

        lblSubtotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSubtotal.setText("SUBTOTAL");

        lblSubTotalNumero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSubTotalNumero.setText("s");

        lblTotal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotal.setText("TOTAL");

        lblTotalNumero.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotalNumero.setText("s");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTotalVentaframe)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCantidadEfectivo)
                    .addComponent(lblEfectivoRecibido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblnroSerie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSerie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNroVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(lblnroVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEfectivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(lblCambio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIVA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubTotalNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIVANumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTotalNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblTipoPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtTotalVentaframe, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblnroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnroVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblEfectivoRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEfectivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCambio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtotal)
                    .addComponent(lblSubTotalNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA)
                    .addComponent(lblIVANumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanelIzquierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreProducto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanelIzquierdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        txtNombreProducto.getAccessibleContext().setAccessibleName("Ingrese el nombre del producto.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("VENTAS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void CBoxRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBoxRegistrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBoxRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBoxRegistros;
    private javax.swing.JPanel JPanelBotonesIzq;
    private javax.swing.JPanel JPanelIzquierdo;
    private javax.swing.JPanel JPanelLogo;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRealizarVenta;
    private javax.swing.JButton btnRealizarVenta1;
    private javax.swing.JButton btnVentas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblEfectivo;
    private javax.swing.JLabel lblEfectivoRecibido;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblIVANumero;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblNroVenta;
    private javax.swing.JLabel lblRegistros;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblSubTotalNumero;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTipoPago;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalNumero;
    private javax.swing.JLabel lblTotalVenta;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JLabel lblnroSerie;
    private javax.swing.JLabel lblnroVenta;
    private javax.swing.JTextField txtCantidadEfectivo;
    private javax.swing.JTextArea txtNombreProducto;
    private javax.swing.JTextField txtTotalVentaframe;
    // End of variables declaration//GEN-END:variables
}
